### ISSUE TITLE
[.257] iteagle games fail to load on Raspberry Pi with lr-mame

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame#292]
Hello,

I am using MAME .239 on a Raspberry Pi 4B. When attempting to load a game using the iteagle BIOS, I only get a black screen for a few seconds and then a crash back to my frontend. This definitely occurs with bbh, carnking, and gtfore01. The example log shown below is for bbh. The libretro errors and warnings about system/driver not found are present even with working games. The warning about no good dump being available also occurs on Windows MAME, where all of the above games load and play.

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame/mamearcade_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/bbh.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
[INFO] [Config]: Loading config from: "/opt/retropie/configs/arcade/retroarch.cfg".
[INFO] [Config]: Appending config "/dev/shm/retroarch.cfg".
[INFO] RetroArch 1.9.14 (Git 06a2367)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Feb  1 2022
[INFO] Version: 1.9.14
[INFO] Git: 06a2367
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Core]: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-mame/mamearcade_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at "/home/pi/.config/retroarch/config/MAME/MAME.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "/home/pi/.config/retroarch/config/MAME/arcade.cfg".
[INFO] [Overrides]: No game-specific overrides found at "/home/pi/.config/retroarch/config/MAME/bbh.cfg".
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Remaps]: Remap directory: "/opt/retropie/configs/arcade/".
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/arcade/bbh.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/arcade/bbh.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] SYSTEM_DIRECTORY: /home/pi/RetroPie/BIOS
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/home/pi/.config/retroarch/downloads".
[libretro INFO] CONTENT_DIRECTORY: /home/pi/.config/retroarch/downloads
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] SAVE_DIRECTORY: /home/pi/RetroPie/roms/arcade/
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] Joystick map: disabled
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[libretro INFO] Joystick map: disabled
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[libretro INFO] AV_INFO: width=640 height=480
[libretro INFO] AV_INFO: max_width=640 max_height=480
[libretro INFO] AV_INFO: aspect_ratio = 1.333333
[libretro INFO] AV_INFO: fps = 60.000000 sample_rate = 48000.000000
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 1920x1080.
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 1 connectors.
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 34 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 60.000000 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 59.940201 Hz
[INFO] [DRM]: Mode 2: (1920x1080i) 1920 x 1080, 30.000000 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 29.970100 Hz
[INFO] [DRM]: Mode 4: (1920x1080) 1920 x 1080, 30.000000 Hz
[INFO] [DRM]: Mode 5: (1920x1080) 1920 x 1080, 29.970100 Hz
[INFO] [DRM]: Mode 6: (1920x1080) 1920 x 1080, 24.000000 Hz
[INFO] [DRM]: Mode 7: (1920x1080) 1920 x 1080, 23.976080 Hz
[INFO] [DRM]: Mode 8: (1680x1050) 1680 x 1050, 59.883251 Hz
[INFO] [DRM]: Mode 9: (1600x900) 1600 x 900, 60.000000 Hz
[INFO] [DRM]: Mode 10: (1280x1024) 1280 x 1024, 75.024673 Hz
[INFO] [DRM]: Mode 11: (1280x1024) 1280 x 1024, 60.019741 Hz
[INFO] [DRM]: Mode 12: (1440x900) 1440 x 900, 59.901459 Hz
[INFO] [DRM]: Mode 13: (1280x800) 1280 x 800, 59.909546 Hz
[INFO] [DRM]: Mode 14: (1152x864) 1152 x 864, 75.000000 Hz
[INFO] [DRM]: Mode 15: (1280x720) 1280 x 720, 60.000000 Hz
[INFO] [DRM]: Mode 16: (1280x720) 1280 x 720, 59.940201 Hz
[INFO] [DRM]: Mode 17: (1024x768) 1024 x 768, 75.028580 Hz
[INFO] [DRM]: Mode 18: (1024x768) 1024 x 768, 70.069359 Hz
[INFO] [DRM]: Mode 19: (1024x768) 1024 x 768, 60.003841 Hz
[INFO] [DRM]: Mode 20: (832x624) 832 x 624, 74.551270 Hz
[INFO] [DRM]: Mode 21: (800x600) 800 x 600, 75.000000 Hz
[INFO] [DRM]: Mode 22: (800x600) 800 x 600, 72.187569 Hz
[INFO] [DRM]: Mode 23: (800x600) 800 x 600, 60.316540 Hz
[INFO] [DRM]: Mode 24: (720x480) 720 x 480, 60.000000 Hz
[INFO] [DRM]: Mode 25: (720x480) 720 x 480, 59.940060 Hz
[INFO] [DRM]: Mode 26: (720x480i) 720 x 480, 30.001110 Hz
[INFO] [DRM]: Mode 27: (720x480i) 720 x 480, 29.970030 Hz
[INFO] [DRM]: Mode 28: (640x480) 640 x 480, 75.000000 Hz
[INFO] [DRM]: Mode 29: (640x480) 640 x 480, 72.808800 Hz
[INFO] [DRM]: Mode 30: (640x480) 640 x 480, 66.666664 Hz
[INFO] [DRM]: Mode 31: (640x480) 640 x 480, 60.000000 Hz
[INFO] [DRM]: Mode 32: (640x480) 640 x 480, 59.940475 Hz
[INFO] [DRM]: Mode 33: (720x400) 720 x 400, 70.081665 Hz
[INFO] [GL]: Found GL context: "kms".
[INFO] [GL]: Detecting screen resolution: 1920x1080.
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0xa133ab28.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.1 Mesa 19.3.2.
[INFO] [GL]: Using resolution 1920x1080.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [udev]: Keyboard #0: "SindenCameraG" (/dev/input/event5).
[INFO] [udev]: Keyboard #1: "Unknown SindenLightgun Keyboard" (/dev/input/event1).
[INFO] [udev]: Keyboard #2: "Logitech Wireless Keyboard PID:4023" (/dev/input/event0).
[INFO] [udev]: Mouse #0: "Unknown SindenLightgun Mouse" (ABS) /dev/input/event2
[INFO] [udev]: Mouse #1: "Logitech Wireless Mouse" (REL) /dev/input/event3
[INFO] [udev]: Pad #0 (/dev/input/event4) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event4) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: "freetype".
[INFO] [Video]: Found display server: "null".
[INFO] ALSA: Using floating point format.
[INFO] ALSA: Period size: 480 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: "freetype".
[INFO] [Font]: Using font rendering backend: "freetype".
[INFO] [Font]: Using font rendering backend: "freetype".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/opt/retropie/configs/arcade/content_favorites.lpl".
[libretro INFO] Starting game:/home/pi/RetroPie/roms/arcade/bbh.zip
[libretro INFO] Game name: bbh, Game description: Big Buck Hunter (v1.00.14)
[libretro ERROR] System not found: arcade
[libretro WARN] Driver arcade not found -1
[libretro INFO] Creating frontend for game: bbh
[libretro INFO] Softlists: 1
Adding monitor screen0 (640 x 480) a:1.333333
[libretro INFO] SOURCE FILE: ../../../../../src/mame/drivers/iteagle.cpp
[libretro INFO] PARENT: iteagle
[libretro INFO] NAME: bbh
[libretro INFO] DESCRIPTION: Big Buck Hunter (v1.00.14)
[libretro INFO] YEAR: 2000
[libretro INFO] MANUFACTURER: Incredible Technologies
[libretro WARN] e2-bbh0.u53 NOT FOUND (NO GOOD DUMP KNOWN) (tried in bbh iteagle)
WARNING: the machine might not run correctly.
[libretro INFO] RES:0
[libretro INFO] MAIN FIRST
[INFO] [Environ]: SET_GEOMETRY: 512x384, Aspect: 1.333.
w:512 h:384 a:1.333333
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1304: 30349 Segmentation fault      /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame/mamearcade_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/bbh.zip" --verbose --appendconfig /dev/shm/retroarch.cfg

```

**Comment by StormedBubbles** [comment]
I should also mention that line 1304 of the runcommand.sh mentioned on the last line of my log is

`eval $COMMAND </dev/tty &>>"$LOG"`

That particular line is part of this code block:

```
function launch_command() {
    local ret
    # escape $ to avoid variable expansion (eg roms containing $!)
    COMMAND="${COMMAND//\$/\\\$}"
    # launch the command
    echo -e "Parameters: $@\nExecuting: $COMMAND" >>"$LOG"
    if [[ "$CONSOLE_OUT" -eq 1 ]]; then
        # turn cursor on
        tput cnorm
        eval $COMMAND </dev/tty 2>>"$LOG"
        ret=$?
        tput civis
    else
        eval $COMMAND </dev/tty &>>"$LOG"
        ret=$?
    fi
    return $ret
}

**Comment by StormedBubbles** [comment]
_Something_ has changed between .239 and .242. `bbh` and `carnking` no longer give me a segmentation fault. I get to a boot screen and pass the "FILESYSTEM CHECKS," but then the emulator freezes at the "Disk Load completed" message. Windows MAME .242 sees the exact same messages but gets past that loading message and goes into the game. I didn't check `gtfore01` again because I figured it'll just have the same issue.

**Comment by nemo93** [comment]
@StormedBubbles hello! Is this still happening on **.256** please?

**Comment by StormedBubbles** [comment]
Hey, thanks for commenting. I can take a look sometime over the next few days. As with Time Crisis, I find it confusing that these games load up and play with Libretro MAME on Windows but fail for some reason on Raspberry Pi (potential performance issues aside).

**Comment by StormedBubbles** [comment]
@nemo93 Still happens with lr-mame updated to .257 as of commit 1ede3ae. I tried with Carnival King this time. The game passes the two drive checks, finds the modem, finds the CD-ROM but determines that no disk is in the drive, tells me it successfully loaded from the hard drive, but then locks up at the "Disk Load completed" message. I have to do a hard reset on my Raspberry Pi at that point.

**Comment by nemo93** [comment]
@StormedBubbles most likely your issue is related to a specific compilation flag. After adding `-fsigned-char` flag for my device/RPi4 everything worked as expected. [Thread](https://retropie.org.uk/forum/post/290184) on the Retropie's forum for reference which also contains the updated binary for that device. Perhaps you can try that binary and see if it makes any difference?

Thanks a lot @sonninnos @grant2258 for the find and testing!

**Comment by StormedBubbles** [comment]
Hey @nemo93 thanks for pursuing this and following up. With that new binary, Carnival King does not freeze my Pi anymore at the boot screen. However, the game still just hangs there. I can move the MAME gun cursor around and open/close the RetroArch and MAME tab menus without issue, though. I left my Pi on that screen for over an hour and never got past it. The controls are very sluggish, so I anticipate this and other `iteagle` games not even being functional enough to play on a Raspberry Pi anyway.

For reference in case you want to try launching these games from a frontend, some of them are CHD only and require special considerations. I launch them by putting the CHD in the appropriate sub-folder of my ROMs folder and creating an empty zipped folder as the "ROM." So for Carnival King, I have the CHD located in `/roms/arcade/carnking/` and an empty `carnking.zip` in `/roms/arcade/` that I select in EmulationStation to launch the game (all via RetroPie). If you do something different and get a different experience, please let me know!

Off-topic: Arcade Time Crisis has been a white whale for me, so it's good to have that functional now. Performance is poor on my Pi, but I'm hoping that this same trick is applicable to older versions of MAME (which have similar issues with this game). I got Time Crisis to work on my own builds of MAME .245 and .174 ("2016"), but performance is only minimally better than .257 (if at all). Compounding this is the game having an annoying bug in pre-.203 MAME. Regardless, Point Blank 2 magically works at or near full speed in MAME .139 ("2010"), while Judge Dredd likewise does so in .160 ("2015"). Perhaps this discussion could be migrated to the RetroPie forum, but I'm curious if you have any insight on compiling 2010 or 2015 in such a way that Time Crisis is accessible. If it were to be at a playable speed at all on Pi, I figure 2010 or 2015 would be good candidates to try. The trick with adding that extra piece to the installation script did not work for either of those cores for me. 2015 didn't like that command at all and wouldn't even compile.

**Comment by nemo93** [comment]
@StormedBubbles thanks! Great feedback. This time I had a quick look at `carnking` and I can reproduce the behavior you describe. My RPi4 is maxed out shortly after the `Disk Load completed` message. It's similar to the `aleck64` driver as discussed [here](https://github.com/libretro/mame/issues/420#issuecomment-1674433033). 

There's no issue though. Simply the RPi is not powerful enough to run these games. I'm afraid no compile flag will help at this point only a more powerful device will.

Regarding Time Crisis honestly even if it's running slow on RPi, I find it somehow playable (not for too long though!). Judge Dredd is running lot better and is almost fullspeed. Yet as for the above I doubt adding or tweaking the compilation process will get those games to run at fullspeed. Only a (much) more powerful device will.

In the meantime, I still recommend to close that ticket off as there's no bug here and games for that specific driver are running. If you have a RPi4 go [get the binary](https://retropie.org.uk/forum/post/290184) compiled with the "magic" flag as it's the best binary you could get for that device. Then feel free to raise any findings or concerns about `lr-mame` for RPi/Retropie on Retropie forum. It's always nice to share info and feedback with others 😃

**Comment by sonninnos** [comment]
The magic flag is also now the default with all platforms, so build away.

**Comment by MistyDreams** [comment]
@StormedBubbles  for mame2010 change as described below. 

https://github.com/libretro/mame2010-libretro/blob/5f524dd5fca63ec1dcf5cca63885286109937587/Makefile#L58C27-L58C27
```
 CCOMFLAGS = -DDISABLE_MIDI -fsigned-char 
```
and compile it for yourself. I can take a look at 2015 if you like but in not sure if these cores are still maintained.

edit:
for 2015 add it here https://github.com/libretro/mame2015-libretro/blob/2599c8aeaf84f62fe16ea00daa460a19298c121c/Makefile#L88

I think the issue for this core is resolved though.

**Comment by StormedBubbles** [comment]
Thanks @MistyDreams for the tips on 2010 and 2015. They both compiled fine, but I still experience the same issues I experienced previously with Time Crisis in those cores.

2010: The game and RetroArch freeze completely before the game has the chance to check that SUBCPU. Loads and plays fine in the same core on Windows.

2015: The game passes all of the tests but then freezes on a black screen right after that. This core isn't available in the RetroArch downloader on Windows, so I haven't checked it there.

In both cases, I have no control over RetroArch and have to do a hard reset on my Pi.

Anyway, I will close this issue as it is resolved.
